# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - nodebb-f24

on:
  push:
    branches:
      - f24
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Set up NodeBB
        run: |
          ./nodebb setup '{"url":"localhost:443", \
            "admin:username": "admin", \
            "admin:password": "${{ secrets.ADMIN_PASSWORD }}", \
            "admin:password:confirm": "${{ secrets.ADMIN_PASSWORD }}", \
            "admin:email": "rohanpadhye@cmu.edu", \
            "database": "redis", \
            "host": "${{ secrets.REDIS_HOST }}", \
            "port":"6380", \
            "password": "${{ secrets.REDIS_PASSWORD }}" }'
          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nodebb-f24'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BFAB97B1AB1441ACA7C63280F91AD3F3 }}
          package: .
